function ChooseRegion () 
{
	/* Window code generated by Prefiniti Development System 1.0.3 */

	var CR_handle = 'ChooseRegion';
	var wRef = p_session.Framework.FindWindow(CR_handle);
	
	if (!wRef) {
		var CR_title  = 'Choose Region';
		var CR_icon   = new PIcon('/graphics/world.png', P_SMALLICON);
		var CR_rect   = new PAutoRect(498, 496);
		var CR_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var CR_MessageHandler  = null;
		var CR_BackgroundColor = new PColor(255, 255, 255);
	
		var CR_window = new PWindow(CR_handle, CR_title, CR_rect, CR_icon, CR_style, CR_MessageHandler, CR_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(CR_window);
	}
	
	var orc = function () {
		p_session.Framework.SetFocus(CR_handle);
	};
	
	CR_ClientAreaURL = '/Framework/CoreSystem/HTMLResources/ChooseRegion.cfm';
	wRef.LoadClientArea(CR_ClientAreaURL, orc);
}