/*
 * QuickAlerts.js
 * desktop notifications for Prefiniti
 *
 * Author: jpw
 * Created: 3/7/2009
 *
 * Copyright (C) 2009, AJL Intel-Properties, LLC
 *
 */

var AlertsShown = 0;

function QuickAlert(Icon, Text, Duration)
{
	this.Icon = Icon;
	this.Text = Text;
	this.Duration = Duration;
	this.Handle = "QuickAlert_" + GetUnique();
	this.wRef = null;
}

QuickAlert.prototype.Show = function () {
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = this.Handle;
	 
	this.wRef = p_session.Framework.FindWindow(TP_handle);
	if (!this.wRef) {
		var TP_title  = 'Quick Alert';
		var TP_icon   = new PIcon('/graphics/pi-16x16.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(350, 150);
		var TP_style  = WS_ALLOWCLOSE | WS_BORDERLESS;
		var TP_MessageHandler  = null;
		var TP_BackgroundColor = new PColor(0, 0, 0);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		this.wRef = p_session.Framework.CreateWindow(TP_window);	
	}

	var pClientArea = new PElement(this.Handle + "_ClientArea");
	
	pClientArea.LoadText('<div align="center" style="width:100%; height:100%; background-color:black; color:white; font-size:24px;"><p><img src="' + this.Icon + '" align="absmiddle"> ' + this.Text + "</p></div>");
	
	if (this.Duration > 0) {
		window.setTimeout("KillQA('" + this.Handle + "');", this.Duration);
	}
	
};


function KillQA(handle)
{
	p_session.Framework.PostLocalMessage(handle, IWC_REQUESTCLOSE, C_WINDOWMANAGER, null);	
	
}