/*
 * RainForest.js
 *
 * Support for inviting Rain Forest users
 */
 
 
 
function RainforestInvite()
{
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = 'RainforestInvite';
	 
	var wRef = p_session.Framework.FindWindow(TP_handle);
	if (!wRef) {
		var TP_title  = 'Add Users by Phone Number';
		var TP_icon   = new PIcon('/graphics/user_add.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(640, 480);
		var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_ALLOWREFRESH | WS_ALLOWRESIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var TP_MessageHandler  = null;
		var TP_BackgroundColor = new PColor(255, 255, 255);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		wRef = p_session.Framework.CreateWindow(TP_window);	
	}
	TP_ClientAreaURL = '/Framework/CoreSystem/Widgets/DPnl/Panels/Clubs/TheRainForest/ClientRegistration.cfm';
	wRef.LoadClientArea(TP_ClientAreaURL);
	 
	/* TP_ToolbarURL = 'ToolbarFile';
	wRef.LoadToolbarStrip(TP_ToolbarURL); */
}

function RFAddUserSubmit(PhoneNumber, CarrierSuffix, EMail)
{
	var wRef = p_session.Framework.FindWindow('RainforestInvite');
	
	if (wRef) {
		var url;
		url = '/Framework/CoreSystem/Widgets/DPnl/Panels/Clubs/TheRainForest/ClientRegistrationSubmit.cfm';
		url += '?PhoneNumber=' + escape(PhoneNumber);
		url += '&EMail=' + escape(EMail);
		url += "&CarrierSuffix=" + escape(CarrierSuffix);
	
		wRef.LoadClientArea(url);
		return true;
	}
	else {
		return false;
	}
}