function doUpload()
{
	window.open("","uploadStatusWindow","width=420,height=220,toolbar=0"); 
    var a = window.setTimeout("document.uploadFile.submit();", 500);
}

function cmsMapAssociation(file_id)
{
	var url;
	url = '/contentmanager/components/cms_map_association.cfm?file_id=' + escape(file_id);
	
	AjaxLoadPageToWindow(url, 'Associate to Subdivision');
}

function updateFileList(project_id)
{
	/* /contentManager/components/fileList.cfm */
	//alert('updateFileList() called.');
	AjaxLoadPageToDiv('fileList', 'http://www.prefiniti.com/contentManager/components/fileList.cfm?id=' + project_id);
	showDivC('fileList');
}

function viewFile(path)
{
	window.open(path,"fileViewWindow","width=1000,height=700,toolbar=0,menubar=1,scrollbars=1"); 
}

function deleteFile(path, projectID, fileID)
{
		var url;
		url = '/contentManager/components/fileDeleteConfirm.cfm?path=' + escape(path);
		url += '&projectID=' + escape(projectID);
		url += '&fileID=' + escape(fileID);
		
		AjaxLoadPageToDiv('tcTarget', url);
}

function doDelete(path, fileID, projectID)
{
		var url;
		url = '/contentManager/components/fileDeleteSubmit.cfm?path=' + escape(path);
		url += '&fileID=' + escape(fileID);
		url += '&projectID=' + escape(projectID);
		
		AjaxLoadPageToDiv('tcTarget', url);
}


function uploadSurveyMap(id)
{
	var url;
	url = "/contentManager/components/surveyMapUpload.cfm?subdivisionID=" + escape(id);
	
	AjaxLoadPageToDiv('tcTarget', url);
}

function copyFile(src_name, src_dir, src_id, tgt_dir, tgt_id, t_div)
{
	var url;
	url = "/contentManager/components/fileCopy.cfm?src_name=" + escape(src_name);
	url += "&src_dir=" + escape(src_dir);
	url += "&src_id=" + escape(src_id);
	url += "&tgt_dir=" + escape(tgt_dir);
	url += "&tgt_id=" + escape(tgt_id);
	
	AjaxLoadPageToDiv(t_div, url);
}


function getUploader(filter, filter_description, max_files, post_target)
{
	var tmp;
// Check to see if SWFUpload is available
	if (typeof(SWFUpload) === "undefined") return(null);

	// Instantiate a SWFUpload Instance
	tmp = new SWFUpload({
		// Backend Settings
		upload_url: post_target,	// I can pass query strings here if I want
		
		// File Upload Settings
		file_size_limit : "3002400",	// 300MB
		file_types : filter,
		file_types_description : filter_description,
		file_upload_limit : 20,

		// Flash Settings
		flash_url : "/contentmanager/swfupload.swf",	// Relative to this file

		// UI Settings
		ui_container_id : "stdUpload",		
		degraded_container_id : "degUpload",
		button_image_url : "../graphics/Get_Files_32.png",	// Relative to the SWF file
		button_placeholder_id : "SWFU",
		button_width: 32,
		button_height: 32,

		file_dialog_start_handler : fileDialogStart,
		file_queued_handler : fileQueued,
		file_queue_error_handler : fileQueueError,
		file_dialog_complete_handler : fileDialogComplete,
		upload_start_handler : uploadStart,
		upload_progress_handler : uploadProgress,
		upload_error_handler : uploadError,
		upload_success_handler : uploadComplete,
		file_complete_handler : fileComplete,
		swfupload_loaded_handler : uploaderReady,
		
		// Debug Settings
		debug: false		// For the purposes of this demo I wan't debug info shown
	});	
	
	tmp.customSettings.progressTarget = "FileUploadProgressArea";
	tmp.customSettings.cancelButtonId = "cancelFUpload";
	return(tmp);
}

function uploaderReady () 
{
	//glob_uploader.selectFiles();
}


/*glob_uploader = getUploader('*.*', 'All Files', 10, '/contentmanager/components/process_upload.cfm?mode=yay');*/
/*filter, filter_description, max_files, post_target)*/
function cmsPrepareUploader(filter, filter_description, mode, site_id, user_id, basedir, subdir, FolderID)
{
	var url;
	url = '/contentmanager/components/process_upload.cfm?mode=' + escape(mode);
	url += '&site_id=' + escape(site_id);
	url += '&user_id=' + escape(user_id);
	url += '&basedir=' + escape(basedir);
	url += '&subdir=' + escape(subdir);
	
	try {
		url += '&FolderID=' + escape(FolderID);
	}
	catch (ex) {}
	
	//url += '&user_id_n=' + glob_userid;
	
	//showDiv('browseButton');
	
	glob_uploader = getUploader(filter, filter_description, 20, url);

	
//glob_uploader.selectFiles();
}



function cmsBrowseFolder(user_id, basedir, subdir, mode, search_criteria)
{
	
	/* Window code generated by Prefiniti Development System 0.1 */

	var wRef = p_session.Framework.FindWindow('FileBrowser15');
	if (!wRef) {
		var FB_handle = 'FileBrowser15';
		var FB_title  = 'File Browser';
		var FB_icon   = new PIcon('/graphics/folder.png', P_SMALLICON);
		var FB_rect   = new PAutoRect(800, 496);
		var FB_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_ALLOWRESIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var FB_MessageHandler  = null;
		var FB_BackgroundColor = new PColor(255, 255, 255);
	
		var FB_window = new PWindow(FB_handle, FB_title, FB_rect, FB_icon, FB_style, FB_MessageHandler, FB_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(FB_window);
	}

	var url;
	
	url = '/contentmanager/components/cms_browse.cfm?user_id=' + escape(user_id);
	url += '&basedir=' + escape(basedir);
	url += '&mode=' + escape(mode);
	url += '&subdir=' + escape(subdir);
	url += '&search_criteria=' + escape(search_criteria);
	
	if(mode == "site")
	{
		url += '&site_id=' + escape(glob_current_site_id);
	}
	
	
	wRef.LoadClientArea(url);
}

function cmsDlgEditAssociation(assoc_id)
{
	var url;
	url = '/contentmanager/components/cms_edit_association.cfm?assoc_id=' + escape(assoc_id);
	/*url += '&file_name=' + escape(file_name);
	url += '&mode=' + escape(mode);*/
	
	AjaxLoadPageToWindow(url, 'Edit File to Project Association');
}

function cmsDlgAddAssociation(file_id, file_name, mode, default_project)
{
	var url;
	url = '/contentmanager/components/cms_add_association.cfm?file_id=' + escape(file_id);
	url += '&file_name=' + escape(file_name);
	url += '&mode=' + escape(mode);
	url += '&root_project=' + escape(default_project);
	
	AjaxLoadPageToDiv('fsa_module', url);
	showDiv('fsa_dialog');
}

function cmsAddAssociation(file_id, project_id, scope, description, releasable)
{
	var url;
	url = '/contentmanager/components/cms_add_association_sub.cfm?file_id=' + escape(file_id);
	url += '&project_id=' + escape(project_id);
	if (scope == "user") {
		url += '&assoc_type=0';
	}
	else {
		url += '&assoc_type=1';
	}
	url += '&description=' + escape(description);
	if (releasable == true) {
		url += '&releasable=1';
	}
	else {
		url += '&releasable=0';
	}
	
	var onRequestCallback = function() {
		AjaxRefreshTarget();
	};
	
	AjaxLoadPageToDiv('dev-null', url, onRequestCallback);
	hideDiv('fsa_dialog');
}

var last_selected=null;

function cmsSelectFile(id, mode, hideDelete)
{
	var cline;
	var lineRef;
	
	cline = "fileLine_" + id.toString();
	lineRef = AjaxGetElementReference(cline);	
	
	lineRef.style.backgroundColor = "#C0C0C0";
	if (last_selected != null) {
		last_selected.style.backgroundColor = "#EFEFEF";
	}
	last_selected = lineRef;
	
	if (mode == "user") {
		showDiv('cms_send_file');
	}
	else {
		hideDiv('cms_send_file');
	}
	
	
	
	if (hideDelete) {
		hideDiv('cms_delete_file');
	}
	else {
		showDiv('cms_delete_file');
	}
	
	SetValue('current_mode', mode);
	SetValue('selected_file_id', id);
	showDiv('file_action');
}

var fileViewers = 0;

function cmsViewFile(file_id, mode)
{
	if (glob_FrameworkRevision < 2.0) {
		window.open('/contentmanager/components/cms_view_file.cfm?file_id=' + escape(file_id) + '&mode=' + escape(mode) + '&site_id=' + glob_current_site_id);
	}
	else {
		/* Window code generated by Prefiniti Development System 1.0.2 */
	
		fileViewers++;
		
		var wRef = p_session.Framework.FindWindow('CMSPreview_' + fileViewers.toString());
		if (!wRef) {
			var CP_handle = 'CMSPreview_' + fileViewers.toString();
			var CP_title  = 'Prefiniti CMS Preview';
			var CP_icon   = new PIcon('/graphics/page_white.png', P_SMALLICON);
			var CP_rect   = new PAutoRect(640, 480);
			var CP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWREFRESH | WS_SHOWAPPMENU | WS_ENABLEPDM;
			var CP_MessageHandler  = null;
			var CP_BackgroundColor = new PColor(255, 255, 255);
		
			var CP_window = new PWindow(CP_handle, CP_title, CP_rect, CP_icon, CP_style, CP_MessageHandler, CP_BackgroundColor);
		
			wRef = p_session.Framework.CreateWindow(CP_window);
			
		
		} /* wRef */
		CP_ClientAreaURL = '/Framework/CoreSystem/HTMLResources/PCMSPreview.cfm';
		CP_ClientAreaURL += '?file_id=' + escape(file_id);
		CP_ClientAreaURL += '&mode=' + escape(mode);
		CP_ClientAreaURL += '&site_id=' + escape(glob_current_site_id);
		
		wRef.LoadClientArea(CP_ClientAreaURL);
	} /* Framework Rev */
}

function cmsDeleteAssociation(assoc_id)
{
	var ans;
	ans = confirm('Are you sure you wish to disassociate this file from the project?');
	
	if (ans)
	{
		var url;
		url = '/contentmanager/components/cms_delete_association.cfm?assoc_id=' + escape(assoc_id);
		
		hideDiv('assoc_' + assoc_id.toString());
		
		var onRequestCallback = function () {
			AjaxRefreshTarget();
		};
		
		AjaxLoadPageToDiv('dev-null', url, onRequestCallback);
	}
}

function cmsDeleteFile(file_id, mode)
{
	var ans;
	ans = confirm('Are you sure you wish to delete this file?');
	
	if (ans)
	{
		var url;
		url = '/contentmanager/components/cms_file_delete.cfm?file_id=' + escape(file_id);
		url += "&mode=" + escape(mode);
		AjaxNullRequest(url);
		
		hideDiv('fileLine_' + file_id.toString());
	}
}

function cmsRenameFile(file_id, mode, new_name)
{
	var url;
	url = '/contentmanager/components/cms_file_rename.cfm?file_id=' + escape(file_id);
	url += '&mode=' + escape(mode);
	url += '&new_name=' + escape(new_name);
	
	AjaxNullRequest(url);
}

function cmsDescribeFile(file_id, mode, description)
{
	var url;
	url = '/contentmanager/components/cms_file_describe.cfm?file_id=' + escape(file_id);
	url += '&mode=' + escape(mode);
	url += '&description=' + escape(description);
	
	AjaxNullRequest(url);		
}

function cmsLoadMiniBrowser(file_id_target, name_target)
{
	var url;
	url = '/contentmanager/components/cms_minibrowser.cfm?file_id_target=' + escape(file_id_target);
	url += '&name_target=' + escape(name_target);
	
	AjaxLoadPageToDiv('cms_minibrowser_area', url);
	showDiv('cms_minibrowser');
}

function cmsMiniBrowserPick(file_id_target, name_target, file_id, filename)
{
	SetValue(file_id_target, file_id);
	SetValue(name_target, filename);
	
	hideDiv('cms_minibrowser');
}

function cmsSetFilePrivacy(file_id_target, file_id, value)
{
	var url;
	url = '/contentManager/components/set_file_privacy.cfm?file_id=' + escape(file_id);
	url += '&value=' + escape(value);
	
	AjaxLoadPageToDiv(file_id_target, url);
}

function setDesktopBackground(user_id, p_url)
{
	var url;
	url = '/contentManager/components/set_desktop_background.cfm?user_id=' + escape(user_id);
	url += '&p_url=' + p_url;
	
	var onLoadedCallback = function () {
		p_session.Framework.PostLocalMessage('PDesktopWindow', 
											 IWC_SCREENRESIZED, 
											 C_WINDOWMANAGER, 
											 new PDimensions(p_session.ScreenWidth, p_session.ScreenHeight));
	};
	
	AjaxLoadPageToDiv('dev-null', url, onLoadedCallback);
}

function cmsFileInfo(file_id, mode)
{
	/* Window code generated by Prefiniti Development System 0.1 */

	var wRef = p_session.Framework.FindWindow('FilePropsPanel');
	if (!wRef) {
		var FPP_handle = 'FilePropsPanel';
		var FPP_title  = 'File Properties';
		var FPP_icon   = new PIcon('/graphics/page_white_edit.png', P_SMALLICON);
		var FPP_rect   = new PAutoRect(498, 496);
		var FPP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var FPP_MessageHandler  = null;
		var FPP_BackgroundColor = new PColor(255, 255, 255);
	
		var FPP_window = new PWindow(FPP_handle, FPP_title, FPP_rect, FPP_icon, FPP_style, FPP_MessageHandler, FPP_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(FPP_window);
	}
	
	p_session.Framework.SetFocus(FPP_handle);
	
	/* ?mode=#url.mode#&id=#created_file_id# */
	var FPP_ClientAreaURL = '/contentmanager/components/cms_file_options.cfm?view=expanded&mode=' + escape(mode);
	FPP_ClientAreaURL += '&id=' + escape(file_id);
	
	wRef.LoadClientArea(FPP_ClientAreaURL);
}


function BrowseContent(user_id, basedir, subdir, mode, search_criteria) 
{
	/* Window code generated by Prefiniti Development System 1.0.2 */
	
	var wRef = p_session.Framework.FindWindow('ContentBrowser');
	if (!wRef) {
		var CB_handle = 'ContentBrowser';
		var CB_title  = 'Content Browser';
		var CB_icon   = new PIcon('/graphics/pi-16x16.png', P_SMALLICON);
		var CB_rect   = new PAutoRect(640, 480);
		var CB_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var CB_MessageHandler  = null;
		var CB_BackgroundColor = new PColor(255, 255, 255);
	
		var CB_window = new PWindow(CB_handle, CB_title, CB_rect, CB_icon, CB_style, CB_MessageHandler, CB_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(CB_window);

		CB_ClientAreaURL = '/framework/CoreSystem/HTMLResources/ContentBrowser.cfm?userid=' + escape(user_id);
		CB_ClientAreaURL += '&basedir=' + escape(basedir);
		CB_ClientAreaURL += '&mode=' + escape(mode);
		CB_ClientAreaURL += '&subdir=' + escape(subdir);
		CB_ClientAreaURL += '&search_criteria=' + escape(search_criteria);
		
		if(mode == "site")
		{
			CB_ClientAreaURL += '&site_id=' + escape(glob_current_site_id);
		}
		
		
		
		wRef.LoadClientArea(CB_ClientAreaURL);
	
		CB_ToolbarURL = '/framework/CoreSystem/HTMLResources/ContentBrowser_Toolbar.cfm';
		wRef.LoadToolbar(CB_ToolbarURL);
	}
}

function mhCB () 
{
	
}