function loadHelp(topic, text, image)
{
	
	/* Window code generated by Prefiniti Development System 1.0.2 */

	var wRef = p_session.Framework.FindWindow('LegacyHelp');
	if (!wRef) {
		var LH_handle = 'LegacyHelp';
		var LH_title  = 'About Prefiniti';
		var LH_icon   = new PIcon('/graphics/pi-16x16.png', P_SMALLICON);
		var LH_rect   = new PAutoRect(550, 400);
		var LH_style  = WS_ALLOWCLOSE;
		var LH_MessageHandler  = null;
		var LH_BackgroundColor = new PColor(255, 255, 255);
	
		var LH_window = new PWindow(LH_handle, LH_title, LH_rect, LH_icon, LH_style, LH_MessageHandler, LH_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(LH_window);
	}


	var url;
	url = "/help/components/viewHelp.cfm?topic=" + escape(topic);
	url += "&text=" + escape(text);
	url += "&image=" + escape(image);
	
	wRef.LoadClientArea(url);
}

function searchHelp(search_help, search_title, search_keywords, search_full)
{
	var url;
	url = '/help/components/search_help.cfm?search_help=' + escape(search_help);
	url += '&search_title=' + escape(search_title);
	url += '&search_keywords=' + escape(search_keywords);
	url += '&search_full=' + escape(search_full);
	
	AjaxLoadPageToDiv('tcTarget', url);
}