// news feed support

function PNewsFeed(id)
{
	/* Window code generated by Prefiniti Development System 1.0.3 */

	var wRef = p_session.Framework.FindWindow('NewsFeed');
	if (!wRef) {
		var NF_handle = 'NewsFeed';
		var NF_title  = 'News Feed';
		var NF_icon   = new PIcon('/graphics/AppIconResources/crystal_project/16x16/apps/knewsticker.png', P_SMALLICON);
		var NF_rect   = new PAutoRect(800, 400);
		var NF_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var NF_MessageHandler  = null;
		var NF_BackgroundColor = new PColor(255, 255, 255);
	
		var NF_window = new PWindow(NF_handle, NF_title, NF_rect, NF_icon, NF_style, NF_MessageHandler, NF_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(NF_window);
	}
	
	var url = '/Framework/Applications/NewsFeed/Feed.cfm?feed_id=' + escape(id);
	wRef.LoadClientArea(url);
	
	var tburl;
	tburl = "/Framework/Applications/NewsFeed/Feed_Toolbar.cfm?feed_id=" + escape(id);
	wRef.LoadToolbarStrip(tburl);
	
}

function ManageNewsFeeds()
{
	var wRef = p_session.Framework.FindWindow('ManageNewsFeeds');
	if (!wRef) {
		var NF_handle = 'ManageNewsFeed';
		var NF_title  = 'Manage News Feed';
		var NF_icon   = new PIcon('/graphics/AppIconResources/crystal_project/16x16/apps/knewsticker.png', P_SMALLICON);
		var NF_rect   = new PAutoRect(550, 600);
		var NF_style  = WS_DIALOG;
		var NF_MessageHandler  = null;
		var NF_BackgroundColor = new PColor(255, 255, 255);
	
		var NF_window = new PWindow(NF_handle, NF_title, NF_rect, NF_icon, NF_style, NF_MessageHandler, NF_BackgroundColor);
	
		wRef = p_session.Framework.CreateWindow(NF_window);
	}
	
	var url;
	url = "/Framework/Applications/NewsFeed/ManageNewsFeeds.cfm";
	
	wRef.LoadClientArea(url);
	
	
}

function LoadSiteFeeds(site_id, div_id)
{
	var url;
	url = '/Framework/Applications/NewsFeed/SiteFeeds.cfm?site_id=' + escape(site_id);
	
	var targ = 'SiteFeeds_' + site_id;
	
	AjaxLoadPageToDiv(targ, url);
}

function nfSetSubscription(feed_id, user_id, method, value) 
{
	var url;
	url = '/Framework/Applications/NewsFeed/SetSubscription.cfm?feed_id=' + escape(feed_id);
	url += "&user_id=" + escape(user_id);
	url += "&method=" + escape(method);
	url += "&value=" + escape(value);
	
	AjaxLoadPageToDiv("newsActionTrgt", url);
}

function nfCreateStory(feed_id)
{
	var editorBox = "NewsTarget_" + escape(feed_id);
	
	var url = '/Framework/Applications/NewsFeed/CreateStory.cfm?feed_id=' + escape(feed_id);
	
	AjaxLoadPageToDiv(editorBox, url);
}

function nfPostStory(feed_id, event_headline, event_body)
{
	var editorBox = "NewsTarget_" + escape(feed_id);
	
	var url = '/Framework/Applications/NewsFeed/PostToFeed.cfm?feed_id=' + escape(feed_id);
	url += '&event_headline=' + escape(event_headline);
	url += "&event_body=" + escape(event_body);
	
	AjaxLoadPageToDiv(editorBox, url);
}