/*
 * FolderBrowser.js
 * Prefiniti Folder Browser
 *
 * Author: jpw
 * Copyright (C) 2009, AJL Intel-Properties LLC
 */

var BrowserHandle = null;
var CurrentPath = null;
var theUploader = null;

function BrowseFrom(Path, CanGoUp, FolderIcon, ParentFolder)
{
	
	CurrentPath = Path;
	
	
	
	var rhTitle = new KRequestHeaders();
	var rhSections = new KRequestHeaders();
	var rhStartPanel = new KRequestHeaders();
	
	var pathParam = new KRequestParam("Path", Path);
	var canGoUpParam = new KRequestParam("CanGoUp", CanGoUp);
	var parentParam = new KRequestParam("ParentFolder", ParentFolder);
	
	
	rhTitle.Add(pathParam);
	rhTitle.Add(canGoUpParam);
	rhTitle.Add(parentParam);
	
	rhSections.Add(pathParam);
	rhSections.Add(canGoUpParam);
	rhSections.Add(parentParam);
	
	rhStartPanel.Add(pathParam);
	rhStartPanel.Add(canGoUpParam);
	rhStartPanel.Add(parentParam);	
	
	if (!BrowserHandle) {
		var cbCancel = function () {
			return;
		};
		
		var cbItemSelect = function () {
			return;
		};
		
		var cbClose = function () {
			BrowserHandle = null;
		};
		
		var cbError = function (err) {
			TransportError(err, "SysWidget_DPnl", null);
			return;
		};
		
		var msBrowser = new MenuStrip();
		var mnuBrwFile = new Menu("mnuBrwFile");
		var mnuBrwEdit = new Menu("mnuBrwEdit");
		var mnuBrwTools = new Menu("mnuBrwTools");
		
		mnuBrwFile.Add(new MenuItem("Open Location...", "/graphics/link_go.png", "javascript:POpenLocation();"));
		mnuBrwFile.Add(new MenuItem("New Folder...", "/graphics/folder_add.png", "javascript:CreateFolderIn(CurrentPath);"));
		mnuBrwFile.Add(new MenuItem("Folder Properties...", "/graphics/door_out.png", "javascript:PSignOut();"));
		mnuBrwFile.Add(new MenuItem("-", "", ""));
		mnuBrwFile.Add(new MenuItem("Close", "", "javascript:PSignOut();"));
		mnuBrwFile.Generate();
		
		AddMenu(mnuBrwFile);
		
		msBrowser.Add('mnuBrwFile', 'File', 'mnuBrwFile');
		msBrowser.Add('mnuBrwEdit', 'Edit', 'mnuBrwEdit');
		msBrowser.Add('mnuBrwTools', 'Tools', 'mnuBrwTools');
		
		
		BrowserHandle = new DPnl('FolderBrowser',
								CurrentPath + ' - The Prefiniti Network',
								FolderIcon,
								rhTitle,
								rhSections,
								rhStartPanel,
								cbCancel,
								cbItemSelect,
								cbClose,
								cbError,
								msBrowser);
		
		BrowserHandle.Show();
		
		
	}
	else {
		
		BrowserHandle.ReInit('FolderBrowser',
								Path,
								FolderIcon,
								rhTitle,
								rhSections,
								rhStartPanel,
								cbCancel,
								cbItemSelect,
								function () {
									BrowserHandle = null;
								},
								cbError);
	}
	
	
}


function ViewPicture(Path)
{
	
	var rhPath = new KRequestHeaders();
	rhPath.Add(new KRequestParam("Path", Path));
	
	
	var cbCancel = function () {
		return;
	};
	
	var cbItemSelect = function () {
		return;
	};
	
	var cbClose = function () {
		return;
	};
	
	var cbError = function (err) {
		TransportError(err, "SysWidget_DPnl", null);
		return;
	};
	
	var myPanel = new DPnl('PictureViewer',
						   	'Picture Viewer',
			   				'/graphics/images.png',
			   				rhPath,
			   				rhPath,
							rhPath,
							cbCancel,
							cbItemSelect,
							cbClose,
							cbError);
	
	myPanel.Show();	
}

function BrowseHost() 
{

	/* Window code generated by Prefiniti Development System 1.0.3 */
	var BH_handle = 'BrowseHost';
	
	var wRef = p_session.Framework.FindWindow('Template');
	if (!wRef) {
				
				var BH_title  = 'Browse Host';
				var BH_icon   = new PIcon('/graphics/computer.png', P_SMALLICON);
				var BH_rect   = new PAutoRect(640, 480);
				var BH_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_ALLOWREFRESH | WS_ALLOWRESIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
				var BH_MessageHandler  = null;
				var BH_BackgroundColor = new PColor(255, 255, 255);
	 
				var BH_window = new PWindow(BH_handle, 
											BH_title, 
											BH_rect, 
											BH_icon, 
											BH_style, 
											BH_MessageHandler, 
											BH_BackgroundColor);
	 
				wRef = p_session.Framework.CreateWindow(BH_window);
				
	}
	
	BH_ClientAreaURL = '/Framework/CoreSystem/Widgets/DPnl/Panels/FolderBrowser/jumploader.cfm';
	BH_ClientAreaURL += '?DestinationPath=' + escape(CurrentPath);
	BH_ClientAreaURL += '&CreatorID=' + escape(AuthenticationRecord.UserID);
	
	wRef.LoadClientArea(BH_ClientAreaURL);

}

function uploaderStatusChanged(uploader) 
{
	BrowseFrom(CurrentPath);
}

function CreateFolderIn(Path) 
{
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = 'CreateFolderIn';
	 
	var wRef = p_session.Framework.FindWindow(TP_handle);
	if (!wRef) {
				
				var TP_title  = 'Create Folder';
				var TP_icon   = new PIcon('/graphics/folder_add.png', P_SMALLICON);
				var TP_rect   = new PAutoRect(550, 250);
				var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ENABLEPDM;
				var TP_MessageHandler  = null;
				var TP_BackgroundColor = new PColor(255, 255, 255);
	 
				var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
				wRef = p_session.Framework.CreateWindow(TP_window);
	
	}
	TP_ClientAreaURL = '/Framework/CoreSystem/Widgets/DPnl/Panels/FolderBrowser/CreateFolderIn.cfm';
	TP_ClientAreaURL += '?Path=' + escape(Path);
	
	wRef.LoadClientArea(TP_ClientAreaURL);
}

function CommitFolder(path, folder)
{
	var rh = new KRequestHeaders();
	rh.Add(new KRequestParam("Path", path));
	rh.Add(new KRequestParam("Folder", folder));
	rh.Add(new KRequestParam("Creator", AuthenticationRecord.UserID));
	rh.Add(new KRequestParam("Owner", AuthenticationRecord.UserID));
	
	var url = '/Framework/CoreSystem/Widgets/DPnl/Panels/FolderBrowser/CommitFolder.cfm'
	
	var res = KSynchronousRequest(url, rh);
	
	p_session.Framework.PostLocalMessage('CreateFolderIn', IWC_REQUESTCLOSE, C_WINDOWMANAGER, null);
	
	
	var ab = new AlertBox(res, "Create Folder", "/graphics/AppIconResources/crystal_project/32x32/actions/folder_new.png");
	ab.Show();
	
	
}


function POpenLocation() 
{
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = 'OpenPRL';
	 
	var wRef = p_session.Framework.FindWindow(TP_handle);
	if (!wRef) {
		var TP_title  = 'Open Location';
		var TP_icon   = new PIcon('/graphics/link_go.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(320, 250);
		var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_ALLOWREFRESH | WS_ALLOWRESIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var TP_MessageHandler  = null;
		var TP_BackgroundColor = new PColor(255, 255, 255);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		wRef = p_session.Framework.CreateWindow(TP_window);	
	}
	TP_ClientAreaURL = '/Framework/CoreSystem/Widgets/DPnl/Panels/FolderBrowser/POpenLocation.cfm';
	wRef.LoadClientArea(TP_ClientAreaURL);
	 
}

function BrowseWebLink(webLink)
{
	window.open(webLink);
}

function SetProfilePicture(profilePicture) 
{
	var rh = new KRequestHeaders();
	rh.Add(new KRequestParam("ProfilePicture", profilePicture));
	rh.Add(new KRequestParam("UserID", AuthenticationRecord.UserID));
	
	var url = '/Framework/CoreSystem/HTMLResources/SetProfilePicture.cfm';
	
	return KSynchronousRequest(url, rh);
}

function LoadImageTo(TgtEl, ImgPath, Width, Height)
{
	var rh = new KRequestHeaders();
	rh.Add(new KRequestParam("ImgPath", ImgPath));
	rh.Add(new KRequestParam("Width", Width));
	rh.Add(new KRequestParam("Height", Height));
	
	var url = "/Framework/CoreSystem/Widgets/DPnl/Panels/FolderBrowser/LoadImageTo.cfm";
	
	SetInnerHTML(TgtEl, KSynchronousRequest(url, rh));
}