
function windowFunction() 
{
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = 'Template';
	 
	var wRef = p_session.Framework.FindWindow(TP_handle);
	if (!wRef) {
		var TP_title  = 'Template';
		var TP_icon   = new PIcon('/graphics/pi-16x16.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(640, 480);
		var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_ALLOWREFRESH | WS_ALLOWRESIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var TP_MessageHandler  = null;
		var TP_BackgroundColor = new PColor(255, 255, 255);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		wRef = p_session.Framework.CreateWindow(TP_window);	
	}
	TP_ClientAreaURL = 'ClientFile';
	wRef.LoadClientArea(TP_ClientAreaURL);
	 
	TP_ToolbarURL = 'ToolbarFile';
	wRef.LoadToolbarStrip(TP_ToolbarURL);
}