/*
 *  DocumentEditor.js
 *  Prefiniti Document Editor
 *
 * Author: jpw
 * Created: 2/11/2009
 *
 * Copyright (C) 2009, AJL Intel-Properties LLC
 *
 */



var DOCMODE_HTML = 0x00;
var DOCMODE_TEXT = 0x01;
 
var Documents = new Array(1);

function DocumentViewer(Path) {
	var fname = Path.PAF_GetStringAfterLast("/");
	
	Path = Path.PAF_GetStringBeforeLast("/");
	
	var pd = new PDocument(Path, fname, DOCMODE_HTML, null);
	pd.View();
}

function DocumentViewer_PlainText(Path) {
	var fname = Path.PAF_GetStringAfterLast("/");
	
	Path = Path.PAF_GetStringBeforeLast("/");
	
	var pd = new PDocument(Path, fname, DOCMODE_TEXT, null);
	pd.View();
}

function DocumentEditor(Path) {
	var fname = Path.PAF_GetStringAfterLast("/");
	
	Path = Path.PAF_GetStringBeforeLast("/");
	
	var pd = new PDocument(Path, fname, DOCMODE_HTML, null);
	pd.Edit();
}

function DocumentEditor_PlainText(Path) {
	var fname = Path.PAF_GetStringAfterLast("/");
	Path = Path.PAF_GetStringBeforeLast("/");
	var pd = new PDocument(Path, fname, DOCMODE_TEXT, null);
	pd.Edit();
}


function PDocument(Path, FileName, Mode, Close_Callback)
{
	/* externals */
	this.Path = Path;
	this.FileName= FileName;
	this.Mode = Mode;
	this.Close_Callback = Close_Callback;

	/* internals */
	this.Editor = null;
	this.Window = null;
	this.Toolbar = null;
	this.ClientArea = null;
	this.InnerFrame = null;
	this.textareaHandle = null;

	Documents.push(this);
}

function FindDocument(Path, FileName) 
{
	for(doc in Documents) {
		if (Documents[doc].Path == Path) {
			if (Documents[doc].FileName == FileName) {
				return Documents[doc];
			}
		}
	}
	
	return null;
}

function FromHandle (Handle) {
	for (doc in Documents) {
		if (Documents[doc].textareaHandle == Handle) {
			return Documents[doc];
		}
	}
	
	return null;
};

PDocument.prototype.View = function () {
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = 'DocumentViewer_' + GetUnique().toString();
	 
	var wRef = p_session.Framework.FindWindow(TP_handle);
	if (!wRef) {
		var TP_title  = this.FileName + ' - Documents';
		var TP_icon   = new PIcon('/graphics/zoom.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(640, 480);
		var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_ALLOWREFRESH | WS_ALLOWRESIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var TP_MessageHandler  = null;
		var TP_BackgroundColor = new PColor(255, 255, 255);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		wRef = p_session.Framework.CreateWindow(TP_window);	
	}
	
	TP_ClientAreaURL = '/Framework/CoreSystem/Widgets/DocumentEditor/DocumentViewer.cfm';
	TP_ClientAreaURL += '?Path=' + this.Path;
	TP_ClientAreaURL += '&FileName=' + this.FileName;
	
	wRef.LoadClientArea(TP_ClientAreaURL);
	
	 
	
};

PDocument.prototype.Edit = function () {
	
	var myAB = new AlertBox("This version of Prefiniti Documents is FOR DEMONSTRATION PURPOSES ONLY. It will not save your work. ", "Documents", "/graphics/AppIconResources/crystal_project/32x32/actions/flag.png");
	myAB.Show();
	
	writeConsole("Prefiniti DOCUMENTS 0.98");
	writeConsole("Copyright &copy; 2009, AJL Intel-Properties LLC");
	writeConsole("<br>DOCUMENTS: Creating window object...");
	var TP_handle = 'PDocument_' + GetUnique();
	 
	this.Window = p_session.Framework.FindWindow(TP_handle);
	if (!this.Window) {
		var TP_title  = this.FileName + " - Documents";
		var TP_icon   = new PIcon('/graphics/AppIconResources/crystal_project/32x32/apps/kate.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(800, 500);
		var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ALLOWMAXIMIZE | WS_SHOWAPPMENU | WS_ENABLEPDM;
		var TP_MessageHandler  = PDocument_MessageHandler;
		var TP_BackgroundColor = new PColor(255, 255, 255);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		this.Window = p_session.Framework.CreateWindow(TP_window);	
	}
	
	
	this.Toolbar 	= new PElement(TP_handle + "_ToolbarStrip");
	this.ClientArea	= new PElement(TP_handle + "_ClientArea");
	this.InnerFrame	= new PElement(TP_handle + "_InnerFrame");
	writeConsole("DOCUMENTS: Requesting client window from server...");
	/* load the textarea */
	var contentURL = "/Framework/CoreSystem/Widgets/DocumentEditor/DocumentWindow.cfm";
	var contentRH = new KRequestHeaders();
	this.textareaHandle = "TAN_" + TP_handle;
	
	contentRH.Add(new KRequestParam("TAN", this.textareaHandle));
	contentRH.Add(new KRequestParam("PATH", this.Path));
	contentRH.Add(new KRequestParam("FILENAME", this.FileName));
	
	this.ClientArea.LoadText(KSynchronousRequest(contentURL, contentRH));
	
	writeConsole("DOCUMENTS: Requesting toolbar resource from server...");
	
	/* load the toolbar */
	var toolbarURL = "/Framework/CoreSystem/Widgets/DocumentEditor/Toolbar.cfm";
	this.Toolbar.LoadText(KSynchronousRequest(toolbarURL, contentRH));
	
	
	switch (this.Mode) {
		case DOCMODE_HTML:
			writeConsole("DOCUMENTS: We are in HTML mode");
			writeConsole("DOCUMENTS: Initializing FCKeditor 2.6...");
			this.Editor = new FCKeditor(this.textareaHandle);
			this.Editor.BasePath = "/FCKeditor/";
			this.Editor.ToolbarSet = "Prefiniti";
			this.Editor.Width = "100%";
			this.Editor.Height = "100%";
			this.Editor.ReplaceTextarea();
			writeConsole("DOCUMENTS: FCKeditor 2.6 initialized.");
			break;	
		case DOCMODE_TEXT:
			writeConsole("DOCUMENTS: We are in plain text mode");
			break;
	}

	
};

PDocument.prototype.Save = function () {
	writeConsole("DOCUMENTS: Saving document...");
	
	var fullPath = this.Path + "/" + this.FileName;
	
	if (this.Mode == DOCMODE_HTML) {
		var oAPI = FCKeditorAPI.GetInstance(this.textareaHandle);
		var Content = oAPI.GetHTML();
	}
	else {
		var edEl = new PElement(this.textareaHandle);
		var Content = edEl.GetText();
	}
	
	Content.PAF_SaveToFile(fullPath, "");
	
	/*var myAB = new AlertBox("Your work has been saved.", "Documents", "/graphics/AppIconResources/crystal_project/32x32/actions/filesave.png");
	myAB.Show();*/
};

PDocument.prototype.SaveAs = function(Path, FileName) {
	this.Path = Path;
	this.FileName = FileName;
	
	this.Save();
};

PDocument.prototype.AddProduct = function() {
	if(this.Mode != DOCMODE_HTML) {
		var myAb = new AlertBox("Cannot add product links in text-only mode.", "Documents Error", "/graphics/error.png");
		myAb.Show();
		return;
	}
	
	/* Window code generated by Prefiniti Development System 1.0.3 */
	var TP_handle = 'AddProduct';
	 
	var wRef = p_session.Framework.FindWindow(TP_handle);
	if (!wRef) {
		var TP_title  = 'Insert Product';
		var TP_icon   = new PIcon('/graphics/pi-16x16.png', P_SMALLICON);
		var TP_rect   = new PAutoRect(450, 350);
		var TP_style  = WS_ALLOWCLOSE | WS_ALLOWMINIMIZE | WS_ENABLEPDM;
		var TP_MessageHandler  = null;
		var TP_BackgroundColor = new PColor(255, 255, 255);

		var TP_window = new PWindow(TP_handle, TP_title, TP_rect, TP_icon, TP_style, TP_MessageHandler, TP_BackgroundColor);
	 
		wRef = p_session.Framework.CreateWindow(TP_window);	
	}
	
	var elClientArea = new PElement(TP_handle + "_ClientArea");
	
	var dlgURL = "/Framework/CoreSystem/Widgets/DocumentEditor/AddProduct.cfm";
	var dlgRH = new KRequestHeaders();
	dlgRH.Add(new KRequestParam("TAN", this.textareaHandle));
	dlgRH.Add(new KRequestParam("SiteID", AuthenticationRecord.SiteID));
	
	elClientArea.LoadText(KSynchronousRequest(dlgURL, dlgRH));
	
};

PDocument.prototype.InsertProductLink = function(id) {
	var oAPI = FCKeditorAPI.GetInstance(this.textareaHandle);
	
	var ourl = '/Framework/CoreSystem/Widgets/DocumentEditor/ProductLink.cfm';
	var orh = new KRequestHeaders();
	orh.Add(new KRequestParam("id", id));

	oAPI.InsertHtml(KSynchronousRequest(ourl, orh));
};

function Editor_NormalClose() {
	
	return true;
}

function PDocument_MessageHandler(handle, msg_id, sender_component, message_object) 
{
	var WindowObject = p_session.Framework.FindWindow(handle);
	
	
	switch (msg_id) {
		case IWC_REQUESTCLOSE:
		
		break;
	}
	
	p_session.Framework.DefaultMessageHandler(handle, msg_id, sender_component, message_object);	
}
